<?php

namespace CourBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CourRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CourRepository extends EntityRepository
{
}
